version: "3.8"

networks:
  backend:
    driver: bridge

services:
  database:
    image: mysql:8.0.39
    container_name: look-us-mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=look_us_db
      - TZ=Asia/Seoul
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./data/mysql-files:/var/lib/mysql-files
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1

  redis:
    image: redis:latest
    container_name: look-us-redis
    ports:
      - "6379:6379"
    networks:
      - backend
