import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import BottomControlBar from '@/components/bottom-control-bar'
import { cn } from '@/lib/utils'
import { Separator } from '@radix-ui/react-select'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={cn(inter.className)}>
                {/* <Separator className=' my-10' /> */}
                <main
                    className='max-w-5xl mx-auto overflow-scroll 
                                    border bg-background shadow-md md:shadow-md'
                >
                    {children}
                </main>
                {/* <Separator className=' my-[7rem]' /> */}

                {/* TODO: show controlbar if user logged in */}
                <BottomControlBar />
            </body>
        </html>
    )
}
