import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import BottomControlBar from '@/components/bottom-control-bar'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={cn(inter.className)}>
                <main
                    className='max-w-5xl mx-auto overflow-scroll 
                               border bg-background shadow-md md:shadow-md'
                >
                    {children}
                </main>

                {/* Adding the ColorPicker component */}
                <div className='color-picker-container my-8'></div>

                <BottomControlBar />
            </body>
        </html>
    )
}
