import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import BottomControlBar from '@/components/bottom-control-bar'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={cn(inter.className)}>
                <main
                    className='max-w-5xl mt-8 ml-4 mr-4'
                    style={{
                        overflow: 'visible', // 스크롤 해제
                        paddingBottom: '80px', // BottomControlBar의 높이만큼 패딩 추가
                    }}
                >
                    {children}
                </main>
                <BottomControlBar />
            </body>
        </html>
    )
}
