spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 버전에 맞게 설정하세요
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: ${MY_GOOGLE_GCP_URL}
    username: ${MY_GOOGLE_GCP_USERNAME}
    password: ${MY_GOOGLE_GCP_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${MY_GOOGLE_CLIENT_ID}
            client-secret: ${MY_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT} # Redis 서버 포트
      password: ${REDIS_PASSWORD} # 비밀번호 설정이 없는 경우 빈 문자열로 둠
      #      timeout: 5000 # 타임아웃 설정 (밀리초)
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      sentinel:
        username: 'default'

jwt:
  issuer: ${MY_JWT_ISSUER}
  secret_key: ${MY_JWT_SECRET_KEY}

logging:
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 100MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    name: logs/sbb.log
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul"