logging:
  config: classpath:log4j2.xml

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 버전에 맞게 설정하세요
        format_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${MY_DATA_SOURCE}
    username: ${MY_DATA_USERNAME}
    password: ${MY_DATA_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${MY_GOOGLE_CLIENT_ID}
            client-secret: ${MY_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  servlet:
    multipart:
      max-file-size: 1MB # 요청 파일 1개의 사이즈
      max-request-size: 3MB # 요청 파일 전체 사이즈

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT} # Redis 서버 포트
      password: ${REDIS_PASSWORD} # 비밀번호 설정이 없는 경우 빈 문자열로 둠
      #      timeout: 5000 # 타임아웃 설정 (밀리초)
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      sentinel:
        username: 'default'

jwt:
  issuer: ${MY_JWT_ISSUER}
  secret_key: ${MY_JWT_SECRET_KEY}
