spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 버전에 맞게 설정하세요
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${MY_GOOGLE_GCP_URL}
    username: ${MY_GOOGLE_GCP_USERNAME}
    password: ${MY_GOOGLE_GCP_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${MY_GOOGLE_CLIENT_ID}
            client-secret: ${MY_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  issuer: ${MY_JWT_ISSUER}
  secret_key: ${MY_JWT_SECRET_KEY}

logging:
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 100MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    name: logs/sbb.log
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul"
