name: Java CI with Gradle Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v4

    # Make gradlew executable
    - name: Run chmod to make gradlew executable
      run: chmod +x ./backend/gradlew 

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Set environment values
    - name: Set environment values
      run: |
        cd ./backend/src/main/resources
        touch ./env.properties
        echo "${{ secrets.ENV }}" > ./env.properties
      shell: bash
      
    - name: Build with Gradle
      run: ./backend/gradlew clean build -x test
